# Generated by Django 4.2 on 2024-11-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbranch',
            name='locality',
            field=models.CharField(default='', max_length=255),
        ),
    ]
