# Generated by Django 4.2 on 2024-12-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menus', '0002_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
